### ISSUE TITLE
Scientific notation does not work in geom files

### ISSUE THREAD

**Issue by kartikayyer** [European-XFEL/EXtra-geom#250]
Small numbers are written by EXtra-geom as `6.6e-05` or something like that. This uses the letter (`e`) which is not recognized by the reader (only `x`, `y` and `z` are allowed for vectors.

This results in the ridiculous situation where EXtra-geom cannot read the geom files it writes by itself!!

**Comment by tmichela** [comment]
Hi Kartik,

This was already fixed in #163 

Either your environment has an old version of extra-geom, then please upgrade it with the latest release, or the geometry file you are trying to read was generated a long time ago when the bug was still there. As we use the `cfelpyutils` library for reading geom files we cannot change the behavior, unfortunatelly you'll have to edit the file manually in this case.
