### ISSUE TITLE
ePix100 ePix10K : change defaut origin

### ISSUE THREAD

**Issue by tmichela** [European-XFEL/EXtra-geom#98]
EPix detectors are single Module imagers. Currently the reference origin is at the center of the detector. I would suggest to change it to one of it's corner. Any opinion? @takluyver @egorsobolev 

I suspect this geometry isn't used yet (by the fact our data does not match the expected shape), so this change can be done without issue imho (feedback appreciated here)...

**Comment by takluyver** [comment]
I assume that for a single module you wouldn't use it centred on the beam, because it would get damaged?

Egor probably has a better idea than me where the ePix geometry might be used. If he's happy with changing that, it's OK by me.

**Comment by egorsobolev** [comment]
I saw different ways to use ePix. With beamstop, or even at a certain angle to the beam. I put the origin to the center since we have only single module detectors and it is natural for me to locate the informative signal at the center of the detector (e.g. difraction has center). 

But I even didn't think about alternatives. I expect users to change defaults anyway. 

Actually, I would better ask users what they prefer.

**Comment by tmichela** [comment]
Thanks, let's keep it as it is then.
